const mockData = [
  {
    id: 1,
    first_name: 'Loutitia',
    last_name: 'Steaning',
    email: 'lsteaning0@usnews.com',
    date_of_birth: '13/05/1978',
    industry: 'n/a',
    salary: 98803.83,
    years_of_experience: 6.6,
  },
  {
    id: 2,
    first_name: 'Ewen',
    last_name: 'McLewd',
    email: 'emclewd1@bbb.org',
    date_of_birth: '15/12/1991',
    industry: 'Telecommunications Equipment',
    salary: 144392.9,
    years_of_experience: 2.8,
  },
  {
    id: 3,
    first_name: 'Park',
    last_name: null,
    email: null,
    date_of_birth: '11/06/1993',
    industry: 'n/a',
    salary: 101773.01,
    years_of_experience: 1.8,
  },
  {
    id: 4,
    first_name: 'Benson',
    last_name: 'Possek',
    email: 'bpossek3@devhub.com',
    date_of_birth: '01/03/1993',
    industry: 'n/a',
    salary: 141822.61,
    years_of_experience: 3.7,
  },
  {
    id: 5,
    first_name: 'Derril',
    last_name: 'Santorini',
    email: 'dsantorini4@wp.com',
    date_of_birth: '10/10/1991',
    industry: 'Electrical Products',
    salary: 144774.96,
    years_of_experience: 4.1,
  },
  {
    id: 6,
    first_name: 'Lisa',
    last_name: 'Cobb',
    email: 'lcobb5@trellian.com',
    date_of_birth: '22/02/1999',
    industry: 'Major Pharmaceuticals',
    salary: 116433.83,
    years_of_experience: 4.3,
  },
  {
    id: 7,
    first_name: 'Erek',
    last_name: 'Corbould',
    email: 'ecorbould6@blog.com',
    date_of_birth: '10/07/1961',
    industry: 'Steel/Iron Ore',
    salary: 72515.73,
    years_of_experience: 3,
  },
  {
    id: 8,
    first_name: 'Stacee',
    last_name: 'McAdam',
    email: 'smcadam7@pen.io',
    date_of_birth: '26/04/1995',
    industry: 'Computer Software: Prepackaged Software',
    salary: 79521.66,
    years_of_experience: 2.4,
  },
  {
    id: 9,
    first_name: 'Anna-diane',
    last_name: 'Urquhart',
    email: 'aurquhart8@reuters.com',
    date_of_birth: '09/10/1968',
    industry: 'Precious Metals',
    salary: 55216.7,
    years_of_experience: 4,
  },
  {
    id: 10,
    first_name: 'Goldia',
    last_name: 'Axelby',
    email: 'gaxelby9@bizjournals.com',
    date_of_birth: '06/05/1986',
    industry: 'Business Services',
    salary: 58835.13,
    years_of_experience: 6.9,
  },
];

export default mockData;
